use std::panic;

use open_rtf_converter::pdf::audit_passive_pdf_bytes;
use open_rtf_converter::rtf::{Lexer, parse_rtf_bytes_with_options};
use open_rtf_converter::{ConvertOptions, RtfLimits, RtfParseOptions, convert_rtf_to_pdf};

#[test]
fn tokenizer_and_parser_mutation_corpus_return_typed_results_without_panics() {
    let parse_options = RtfParseOptions::browser_safe_defaults();

    for (case_idx, case) in mutation_corpus().into_iter().enumerate() {
        let lex_result =
            panic::catch_unwind(|| Lexer::new(&case, RtfLimits::browser_defaults()).tokenize());
        assert!(
            lex_result.is_ok(),
            "lexer panicked for mutation corpus case {case_idx}: {:?}",
            String::from_utf8_lossy(&case)
        );

        let parse_result =
            panic::catch_unwind(|| parse_rtf_bytes_with_options(&case, &parse_options));
        assert!(
            parse_result.is_ok(),
            "parser panicked for mutation corpus case {case_idx}: {:?}",
            String::from_utf8_lossy(&case)
        );
    }
}

#[test]
fn converter_mutation_corpus_rejects_or_emits_passive_pdf_without_payload_leakage() {
    let options = ConvertOptions {
        diagnostics: true,
        parse_options: RtfParseOptions::browser_safe_defaults(),
    };

    for (case_idx, case) in mutation_corpus().into_iter().enumerate() {
        let convert_result = panic::catch_unwind(|| convert_rtf_to_pdf(&case, &options));
        assert!(
            convert_result.is_ok(),
            "converter panicked for mutation corpus case {case_idx}: {:?}",
            String::from_utf8_lossy(&case)
        );

        let Ok(output) = convert_result.expect("panic checked") else {
            continue;
        };

        audit_passive_pdf_bytes(&output.pdf).expect("converter output must remain passive");
        for forbidden in [
            b"objdata".as_slice(),
            b"objocx",
            b"414243",
            b"pFragments",
            b"calc.exe",
            b"launch.exe",
            b"https://example.com/payload",
            b"/JavaScript",
            b"/EmbeddedFile",
            b"/Launch",
            b"/OpenAction",
            b"/RichMedia",
        ] {
            assert!(
                !output
                    .pdf
                    .windows(forbidden.len())
                    .any(|window| window == forbidden),
                "forbidden payload leaked to PDF for mutation corpus case {case_idx}: {:?}",
                String::from_utf8_lossy(forbidden)
            );
        }
    }
}

fn mutation_corpus() -> Vec<Vec<u8>> {
    let mut cases = Vec::new();
    for seed in seed_corpus() {
        for mutated in mutations(&seed) {
            cases.push(mutated);
        }
    }
    cases
}

fn mutations(seed: &[u8]) -> Vec<Vec<u8>> {
    let mut cases = vec![
        seed.to_vec(),
        with_prefix(seed, b"{"),
        with_suffix(seed, b"}"),
        with_suffix(seed, b"\\bin5 abc"),
        with_suffix(seed, b"{\\*\\unknown{\\object\\objdata 414243}}"),
    ];

    if !seed.is_empty() {
        let mid = seed.len() / 2;
        let mut split_control = Vec::with_capacity(seed.len() + 18);
        split_control.extend_from_slice(&seed[..mid]);
        split_control.extend_from_slice(b"{\\*\\unknown ");
        split_control.extend_from_slice(&seed[mid..]);
        split_control.extend_from_slice(b"}");
        cases.push(split_control);
    }

    cases
}

fn with_prefix(seed: &[u8], prefix: &[u8]) -> Vec<u8> {
    let mut output = Vec::with_capacity(prefix.len() + seed.len());
    output.extend_from_slice(prefix);
    output.extend_from_slice(seed);
    output
}

fn with_suffix(seed: &[u8], suffix: &[u8]) -> Vec<u8> {
    let mut output = Vec::with_capacity(seed.len() + suffix.len());
    output.extend_from_slice(seed);
    output.extend_from_slice(suffix);
    output
}

fn seed_corpus() -> Vec<Vec<u8>> {
    vec![
        rtf(&["{", "\\", "rtf1 hello}"]),
        rtf(&["{", "\\", "rtf1{", "\\", "b bold}}"]),
        rtf(&["{", "\\", "rtf1 ", "\\", "u8217?}"]),
        rtf(&["{", "\\", "rtf1", "\\", "bin3 abc}"]),
        rtf(&["{", "\\", "rtf1", "\\", "'41", "\\", "'42", "\\", "'43}"]),
        rtf(&["{", "\\", "rtf1", "\\", "'GZ}"]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "unknown ignored} visible}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "title Safe title}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst DOCPROPERTY Title}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "adeflang1025",
            "\\",
            "nobrkwrptbl",
            "\\",
            "sprstsp",
            "\\",
            "doctype0",
            "\\",
            "trackmoves0",
            "\\",
            "trackformatting1",
            "\\",
            "validatexml0",
            "\\",
            "showxmlerrors0",
            "\\",
            "saveinvalidxml0",
            "\\",
            "usenormstyforlist Visible",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "trowd",
            "\\",
            "tabsnoovrlp",
            "\\",
            "tdfrmtxtLeft180",
            "\\",
            "tdfrmtxtRight180",
            "\\",
            "tphmrg",
            "\\",
            "tposx720",
            "\\",
            "tpvmrg",
            "\\",
            "tposy360",
            "\\",
            "clFitText",
            "\\",
            "cellx1800 Floating",
            "\\",
            "cell",
            "\\",
            "row}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "sectd",
            "\\",
            "pgnx720",
            "\\",
            "pgny720",
            "\\",
            "sectlinegrid360",
            "\\",
            "sectdefaultcl",
            "\\",
            "sectexpand720",
            "\\",
            "sectspecifycl",
            "\\",
            "sectspecifyl",
            "\\",
            "sectunlocked{",
            "\\",
            "header Page ",
            "\\",
            "chpgn",
            "\\",
            "par}Visible section grid",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "themelang1033",
            "\\",
            "dghspace180",
            "\\",
            "dgvspace180",
            "\\",
            "viewbksp1",
            "\\",
            "viewnobound1",
            "\\",
            "formdisp",
            "\\",
            "jexpand",
            "\\",
            "jcompress",
            "\\",
            "asianbrkrule",
            "\\",
            "nogrowautofit",
            "\\",
            "lytexcttp",
            "\\",
            "noextrasprl",
            "\\",
            "htmautsp Visible compatibility",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "stylesheet{",
            "\\",
            "s1 Heading;}}{",
            "\\",
            "s1 Visible heading",
            "\\",
            "par}{",
            "\\",
            "pard {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst STYLEREF Heading}}",
            "\\",
            "par}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst ADDIN \"Hidden addin\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst PRIVATE \"414243\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst RD \"C:\\\\secret\\\\source.rtf\"}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst NEXTIF \"City\" = \"Paris\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst MERGEREC}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst MERGESEQ}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst ADDRESSBLOCK \\\\f \"<<_COMPANY_>>\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst GREETINGLINE \\\\f \"<<_LAST0_>>\"}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst ASK Client \"Hidden prompt\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst FILLIN \"Secret prompt\"}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst FILENAME \\\\p}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst USERNAME}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "bkmkstart NoteRef}",
            "\\",
            "chftn{",
            "\\",
            "bkmkend NoteRef}{",
            "\\",
            "footnote Footnote}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst NOTEREF NoteRef}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "version12}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst REVNUM}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "userprops{",
            "\\",
            "propname Client}{",
            "\\",
            "staticval Contoso}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst DOCPROPERTY Client}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "docvar {Client}{Contoso}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst DOCVARIABLE Client}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst SET Client \"Contoso\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst REF Client}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "title Safe title}{",
            "\\",
            "author Alice}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst TITLE}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst AUTHOR}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "title Safe title}{",
            "\\",
            "author Alice}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst INFO Title}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst INFO Author}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "creatim",
            "\\",
            "yr2024",
            "\\",
            "mo7",
            "\\",
            "dy5}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst CREATEDATE \\\\@ \"yyyy-MM-dd\"}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst ADVANCE \\\\r 240}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst DATE \\\\@ \"yyyy-MM-dd\"}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst TIME \\\\@ \"HH:mm\"}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "edmins42}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst EDITTIME}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "fonttbl{",
            "\\",
            "f0 Arial;}}Hello}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "colortbl;",
            "\\",
            "red255",
            "\\",
            "green0",
            "\\",
            "blue0;}Hello}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "stylesheet{",
            "\\",
            "s0 Normal;}}{",
            "\\",
            "latentstyles",
            "\\",
            "lsdstimax376",
            "\\",
            "lsdsemihiddendef1 Hidden{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}Visible",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "trowd",
            "\\",
            "trftsWidth3",
            "\\",
            "trwWidth2880 A",
            "\\",
            "cell B",
            "\\",
            "cell",
            "\\",
            "row}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "object",
            "\\",
            "objocx",
            "\\",
            "objdata 414243}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "object{",
            "\\",
            "objdata 414243}{",
            "\\",
            "result visible fallback}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "object{",
            "\\",
            "objdata 414243}{",
            "\\",
            "result{",
            "\\",
            "pict",
            "\\",
            "jpegblip",
            "\\",
            "picwgoal720",
            "\\",
            "pichgoal720 ffd8ffc00011080001000103011100021100031100ffd9}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "fromhtml1",
            "\\",
            "htmlrtf1",
            "\\",
            "b",
            "\\",
            "htmlrtf0 Visible{",
            "\\",
            "*",
            "\\",
            "htmltag <script>414243</script>}{",
            "\\",
            "htmltag Hidden HTML}{",
            "\\",
            "htmlbase https://example.com/payload} after",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst HYPERLINK \"https://example.com/payload\"}{",
            "\\",
            "fldrslt visible link}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst QUOTE \"mixed Case\" \\\\* Lower \\\\* FirstCap}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst SEQ Figure \\\\r 4 \\\\* ROMAN}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst = 27 \\\\* alphabetic}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst = 1234567 \\\\# \"#,##0\"}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst COMPARE 5 > 3 \\\\* ROMAN}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst COMPARE 1 = 1 HIDDEN-TRAIL}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst TOC \\\\o \"1-3\"}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst BIBLIOGRAPHY}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst AUTOTEXT HiddenBlock}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst BARCODE \"Hidden address\" QR}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst MERGEBARCODE \"Hidden merge value\" QR}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst GOTOBUTTON HiddenBookmark \"Visible jump\"}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst CONTROL Forms.CommandButton.1 \"Hidden caption\"}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst HTMLINPUT \"password\" value=\"secret\"}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst SHAPE \\\\* MERGEFORMAT}{",
            "\\",
            "fldrslt Visible drawing fallback}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst SHAPE \\\\* MERGEFORMAT}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 visible{",
            "\\",
            "annotation hidden {",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "shp{",
            "\\",
            "*",
            "\\",
            "shpinst{",
            "\\",
            "sp{",
            "\\",
            "sn pFragments}{",
            "\\",
            "sv calc.exe}}}} visible}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst MACROBUTTON launch.exe Click}{",
            "\\",
            "fldrslt Safe caption}}}",
        ]),
        b"{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{".to_vec(),
        rtf(&["{", "\\", "rtf1", "\\", "bin999999999999999999999 abc}"]),
        rtf(&["{", "\\", "rtf1", "\\", "bin-1 abc}"]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa text}",
        ]),
    ]
}

fn rtf(parts: &[&str]) -> Vec<u8> {
    let mut output = Vec::new();
    for part in parts {
        output.extend_from_slice(part.as_bytes());
    }
    output
}
