use std::panic;

use open_rtf_converter::pdf::audit_passive_pdf_bytes;
use open_rtf_converter::rtf::{Lexer, parse_rtf_bytes_with_options};
use open_rtf_converter::{ConvertOptions, RtfLimits, RtfParseOptions, convert_rtf_to_pdf};

#[test]
fn tokenizer_and_parser_mutation_corpus_return_typed_results_without_panics() {
    let parse_options = RtfParseOptions::browser_safe_defaults();

    for (case_idx, case) in mutation_corpus().into_iter().enumerate() {
        let lex_result =
            panic::catch_unwind(|| Lexer::new(&case, RtfLimits::browser_defaults()).tokenize());
        assert!(
            lex_result.is_ok(),
            "lexer panicked for mutation corpus case {case_idx}: {:?}",
            String::from_utf8_lossy(&case)
        );

        let parse_result =
            panic::catch_unwind(|| parse_rtf_bytes_with_options(&case, &parse_options));
        assert!(
            parse_result.is_ok(),
            "parser panicked for mutation corpus case {case_idx}: {:?}",
            String::from_utf8_lossy(&case)
        );
    }
}

#[test]
fn converter_mutation_corpus_rejects_or_emits_passive_pdf_without_payload_leakage() {
    let options = ConvertOptions {
        diagnostics: true,
        parse_options: RtfParseOptions::browser_safe_defaults(),
        ..ConvertOptions::default()
    };

    for (case_idx, case) in mutation_corpus().into_iter().enumerate() {
        let convert_result = panic::catch_unwind(|| convert_rtf_to_pdf(&case, &options));
        assert!(
            convert_result.is_ok(),
            "converter panicked for mutation corpus case {case_idx}: {:?}",
            String::from_utf8_lossy(&case)
        );

        let Ok(output) = convert_result.expect("panic checked") else {
            continue;
        };

        audit_passive_pdf_bytes(&output.pdf).expect("converter output must remain passive");
        for forbidden in [
            b"objdata".as_slice(),
            b"objocx",
            b"414243",
            b"444546",
            b"pFragments",
            b"calc.exe",
            b"launch.exe",
            b"https://example.com/payload",
            b"FORMTEXT",
            b"FORMCHECKBOX",
            b"FORMDROPDOWN",
            b"ffentrymcr",
            b"datafield",
            b"macc",
            b"mchr",
            b"mbarPr",
            b"mborderBox",
            b"mbrk",
            b"mphant",
            b"mphantPr",
            b"mpos",
            b"bot",
            b"mshow",
            b"mfPr",
            b"mtype",
            b"noBar",
            b"mradPr",
            b"mdegHide",
            b"mgroupChr",
            b"mgroupChrPr",
            b"mfunc",
            b"mfuncPr",
            b"mfName",
            b"mctrlPr",
            b"msty",
            b"bolditalic",
            b"mlimLoc",
            b"meqArrPr",
            b"mlimLowPr",
            b"mlimUppPr",
            b"undOvr",
            b"mopEmu",
            b"mmatrixPr",
            b"mdPr",
            b"mbegChr",
            b"msepChr",
            b"mendChr",
            b"msPrePr",
            b"msSubPr",
            b"msSubSupPr",
            b"msSupPr",
            b"/JavaScript",
            b"/EmbeddedFile",
            b"/Launch",
            b"/OpenAction",
            b"/RichMedia",
        ] {
            assert!(
                !output
                    .pdf
                    .windows(forbidden.len())
                    .any(|window| window == forbidden),
                "forbidden payload leaked to PDF for mutation corpus case {case_idx}: {:?}",
                String::from_utf8_lossy(forbidden)
            );
        }
    }
}

fn mutation_corpus() -> Vec<Vec<u8>> {
    let mut cases = Vec::new();
    for seed in seed_corpus() {
        for mutated in mutations(&seed) {
            cases.push(mutated);
        }
    }
    cases
}

fn mutations(seed: &[u8]) -> Vec<Vec<u8>> {
    let mut cases = vec![
        seed.to_vec(),
        with_prefix(seed, b"{"),
        with_suffix(seed, b"}"),
        with_suffix(seed, b"\\bin5 abc"),
        with_suffix(seed, b"{\\*\\unknown{\\object\\objdata 414243}}"),
    ];

    if !seed.is_empty() {
        let mid = seed.len() / 2;
        let mut split_control = Vec::with_capacity(seed.len() + 18);
        split_control.extend_from_slice(&seed[..mid]);
        split_control.extend_from_slice(b"{\\*\\unknown ");
        split_control.extend_from_slice(&seed[mid..]);
        split_control.extend_from_slice(b"}");
        cases.push(split_control);
    }

    cases
}

fn with_prefix(seed: &[u8], prefix: &[u8]) -> Vec<u8> {
    let mut output = Vec::with_capacity(prefix.len() + seed.len());
    output.extend_from_slice(prefix);
    output.extend_from_slice(seed);
    output
}

fn with_suffix(seed: &[u8], suffix: &[u8]) -> Vec<u8> {
    let mut output = Vec::with_capacity(seed.len() + suffix.len());
    output.extend_from_slice(seed);
    output.extend_from_slice(suffix);
    output
}

fn seed_corpus() -> Vec<Vec<u8>> {
    vec![
        rtf(&["{", "\\", "rtf1 hello}"]),
        rtf(&["{", "\\", "rtf1{", "\\", "b bold}}"]),
        rtf(&["{", "\\", "rtf1 ", "\\", "u8217?}"]),
        rtf(&["{", "\\", "rtf1", "\\", "bin3 abc}"]),
        rtf(&["{", "\\", "rtf1", "\\", "'41", "\\", "'42", "\\", "'43}"]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "pnseclvl1",
            "\\",
            "pnucrm",
            "\\",
            "pnstart1{",
            "\\",
            "pntxta .}}Title",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "fonttbl{",
            "\\",
            "f0 Arial;}{",
            "\\",
            "f1",
            "\\",
            "fcharset2 Symbol;}}{",
            "\\",
            "pntext",
            "\\",
            "pard",
            "\\",
            "plain",
            "\\",
            "f1 ",
            "\\",
            "'b7",
            "\\",
            "tab}",
            "\\",
            "pard",
            "\\",
            "fi-360",
            "\\",
            "li360 Bullet item",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "fonttbl{",
            "\\",
            "f0 Arial;}{",
            "\\",
            "f1",
            "\\",
            "fcharset2 Symbol;}}{",
            "\\",
            "pntext",
            "\\",
            "pard",
            "\\",
            "plain",
            "\\",
            "f1 ",
            "\\",
            "'b7",
            "\\",
            "tab}{",
            "\\",
            "*",
            "\\",
            "pn",
            "\\",
            "pnlvlblt",
            "\\",
            "pnf1{",
            "\\",
            "pntxtb ",
            "\\",
            "'b7}}",
            "\\",
            "pard",
            "\\",
            "fi-360",
            "\\",
            "li360 Bullet item",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "stylesheet{",
            "\\",
            "s1",
            "\\",
            "b Heading;}}",
            "\\",
            "s1 Bold",
            "\\",
            "par",
            "\\",
            "s0 Normal",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "ansi",
            "\\",
            "ansicpg1252{",
            "\\",
            "fonttbl{",
            "\\",
            "f0",
            "\\",
            "froman Times New Roman;}{",
            "\\",
            "f1",
            "\\",
            "fcharset2 Symbol;}}",
            "\\",
            "f0 Normal ",
            "\\",
            "'85",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "stylesheet{",
            "\\",
            "s1",
            "\\",
            "outlinelevel2",
            "\\",
            "cgrid Heading;}}",
            "\\",
            "pard",
            "\\",
            "outlinelevel1",
            "\\",
            "cgrid Visible metadata",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "pard",
            "\\",
            "fi-360",
            "\\",
            "li360",
            "\\",
            "jclisttab",
            "\\",
            "tx360 List item",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "trowd",
            "\\",
            "trgaph108",
            "\\",
            "clbrdrl",
            "\\",
            "brdrs",
            "\\",
            "brdrw30",
            "\\",
            "clbrdrt",
            "\\",
            "brdrs",
            "\\",
            "brdrw30",
            "\\",
            "clbrdrb",
            "\\",
            "brdrs",
            "\\",
            "brdrw30",
            "\\",
            "clbrdrr",
            "\\",
            "brdrs",
            "\\",
            "brdrw30",
            "\\",
            "cellx1200",
            "\\",
            "cellx2400 A",
            "\\",
            "cell B",
            "\\",
            "cell",
            "\\",
            "row",
            "\\",
            "pard",
            "\\",
            "intbl C",
            "\\",
            "cell D",
            "\\",
            "cell",
            "\\",
            "row After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "trowd",
            "\\",
            "trbrdrh",
            "\\",
            "brdrdb",
            "\\",
            "brdrw80",
            "\\",
            "trbrdrv",
            "\\",
            "brdrdot",
            "\\",
            "brdrw60",
            "\\",
            "cellx1200 A",
            "\\",
            "cell",
            "\\",
            "cellx2400 B",
            "\\",
            "cell",
            "\\",
            "cellx3600 C",
            "\\",
            "cell",
            "\\",
            "row}",
        ]),
        rtf(&["{", "\\", "rtf1", "\\", "'GZ}"]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "unknown ignored} visible}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "title Safe title}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst DOCPROPERTY Title}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "adeflang1025",
            "\\",
            "nobrkwrptbl",
            "\\",
            "sprstsp",
            "\\",
            "doctype0",
            "\\",
            "trackmoves0",
            "\\",
            "trackformatting1",
            "\\",
            "validatexml0",
            "\\",
            "showxmlerrors0",
            "\\",
            "saveinvalidxml0",
            "\\",
            "usenormstyforlist Visible",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "nouicompat",
            "\\",
            "rsidroot123456{",
            "\\",
            "*",
            "\\",
            "rsidtbl ",
            "\\",
            "rsid123456{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}",
            "\\",
            "rsid123456",
            "\\",
            "vertdoc",
            "\\",
            "wraptrsp",
            "\\",
            "sprsspbf",
            "\\",
            "sprsbsp Visible session",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "xmlnstbl {",
            "\\",
            "xmlns1 http://schemas.example/payload}}{",
            "\\",
            "*",
            "\\",
            "datastore 414243 {",
            "\\",
            "object",
            "\\",
            "objdata 414243}}Before {",
            "\\",
            "xmlopen{",
            "\\",
            "xmlattrname secret}{",
            "\\",
            "xmlattrvalue 414243}tagged ",
            "\\",
            "xmlclose} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "md{",
            "\\",
            "mdPr{",
            "\\",
            "mbegChr (}{",
            "\\",
            "mendChr )}}{",
            "\\",
            "me{",
            "\\",
            "mtext x+1}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mrad{",
            "\\",
            "mradPr launch.exe objdata 414243 ",
            "\\",
            "u67?",
            "\\",
            "'44{",
            "\\",
            "mdegHide1}}{",
            "\\",
            "mdeg{",
            "\\",
            "mtext hidden}}{",
            "\\",
            "me{",
            "\\",
            "mtext x}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "meqArr{",
            "\\",
            "meqArrPr calc.exe objdata 414243}{",
            "\\",
            "me{",
            "\\",
            "mtext A=1}}{",
            "\\",
            "mlimLow{",
            "\\",
            "mlimLowPr launch.exe}{",
            "\\",
            "me{",
            "\\",
            "mtext lim}}{",
            "\\",
            "mlim{",
            "\\",
            "mtext x=0}}}{",
            "\\",
            "mlimUpp{",
            "\\",
            "mlimUppPr https://example.com/payload}{",
            "\\",
            "me{",
            "\\",
            "mtext max}}{",
            "\\",
            "mlim{",
            "\\",
            "mtext n}}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "msSubSup{",
            "\\",
            "msSubSupPr calc.exe {",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext x}}{",
            "\\",
            "msub{",
            "\\",
            "msSubPr launch.exe}{",
            "\\",
            "mtext i}}{",
            "\\",
            "msup{",
            "\\",
            "msSupPr https://example.com/payload}{",
            "\\",
            "mtext 2}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mgroupChr{",
            "\\",
            "mgroupChrPr{",
            "\\",
            "mchr ",
            "\\",
            "u9182?}{",
            "\\",
            "mpos bot}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext x+1}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 A{",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mbox{",
            "\\",
            "mboxPr{",
            "\\",
            "mopEmu1}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext +}}}}}B",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 A{",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mbox{",
            "\\",
            "mboxPr{",
            "\\",
            "mopEmu0}}{",
            "\\",
            "me{",
            "\\",
            "mtext -}}}}}B",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "macc{",
            "\\",
            "maccPr{",
            "\\",
            "mchr ^}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext x}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "md{",
            "\\",
            "mdPr{",
            "\\",
            "mbegChr [}{",
            "\\",
            "msepChr ;}{",
            "\\",
            "mendChr ]}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext A}}{",
            "\\",
            "me{",
            "\\",
            "mtext B}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "md{",
            "\\",
            "mdPr{",
            "\\",
            "mbegChr (}{",
            "\\",
            "msepChr calc.exe}{",
            "\\",
            "mendChr )}}{",
            "\\",
            "me{",
            "\\",
            "mtext C}}{",
            "\\",
            "me{",
            "\\",
            "mtext D}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mphant{",
            "\\",
            "mphantPr{",
            "calc.exe objdata 414243 ",
            "\\",
            "u65?",
            "\\",
            "'42",
            "\\",
            "mshow1}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext VisiblePhantom}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mphant{",
            "\\",
            "mphantPr{",
            "launch.exe https://example.com/payload objdata 444546 ",
            "\\",
            "u67?",
            "\\",
            "'44",
            "\\",
            "mshow0}}{",
            "\\",
            "me{",
            "\\",
            "mtext HIDDEN-PHANTOM-PAYLOAD}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mbox{",
            "\\",
            "mboxPr{",
            "\\",
            "mbrk0 }{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext First}}{",
            "\\",
            "mtext Second}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mtext{",
            "\\",
            "mctrlPr{",
            "\\",
            "msty bolditalic}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}Styled}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mtext{",
            "\\",
            "mctrlPr{",
            "\\",
            "msty calc.exe}}Plain}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mnary{",
            "\\",
            "mnaryPr{",
            "\\",
            "mchr ",
            "\\",
            "u8721?}{",
            "\\",
            "mlimLoc undOvr}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "msub{",
            "\\",
            "mtext low}}{",
            "\\",
            "msup{",
            "\\",
            "mtext high}}{",
            "\\",
            "me{",
            "\\",
            "mtext body}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mnary{",
            "\\",
            "mnaryPr{",
            "\\",
            "mchr ",
            "\\",
            "u8721?}{",
            "\\",
            "mlimLoc calc.exe}}{",
            "\\",
            "msub{",
            "\\",
            "mtext low}}{",
            "\\",
            "msup{",
            "\\",
            "mtext high}}{",
            "\\",
            "me{",
            "\\",
            "mtext body}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mf{",
            "\\",
            "mfPr{",
            "\\",
            "mtype noBar}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "mnum{",
            "\\",
            "mtext A}}{",
            "\\",
            "mden{",
            "\\",
            "mtext B}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mf{",
            "\\",
            "mfPr{",
            "\\",
            "mtype calc.exe}}{",
            "\\",
            "mnum{",
            "\\",
            "mtext A}}{",
            "\\",
            "mden{",
            "\\",
            "mtext B}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mmatrix{",
            "\\",
            "mmatrixPr{",
            "\\",
            "msepChr ;}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "mr{",
            "\\",
            "marg{",
            "\\",
            "mtext A}}{",
            "\\",
            "marg{",
            "\\",
            "mtext B}}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mmatrix{",
            "\\",
            "mmatrixPr{",
            "\\",
            "msepChr calc.exe}}{",
            "\\",
            "mr{",
            "\\",
            "marg{",
            "\\",
            "mtext A}}{",
            "\\",
            "marg{",
            "\\",
            "mtext B}}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "macc{",
            "\\",
            "maccPr{",
            "\\",
            "mchr ",
            "\\",
            "u773?}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext x}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mbar{",
            "\\",
            "mbarPr{",
            "calc.exe objdata 414243 ",
            "\\",
            "u65?",
            "\\",
            "'42",
            "\\",
            "mpos bot}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext UnderBar}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mborderBox{",
            "\\",
            "mborderBoxPr{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext x+1}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mgroupChr{",
            "\\",
            "mgroupChrPr{",
            "\\",
            "mchr ",
            "\\",
            "u9182?}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext x+1}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "mmath{",
            "\\",
            "moMath{",
            "\\",
            "mfunc{",
            "\\",
            "mfuncPr{calc.exe {",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "mfName{",
            "\\",
            "mtext sin}{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}{",
            "\\",
            "me{",
            "\\",
            "mtext x}}}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "pict",
            "\\",
            "jpegblip",
            "\\",
            "bliptag123",
            "\\",
            "blipuid 0123456789abcdef0123456789abcdef{",
            "\\",
            "picprop{",
            "\\",
            "sp{",
            "\\",
            "sn pFragments}{",
            "\\",
            "sv calc.exe}}}",
            "ffd8ffc00011080001000103011100021100031100ffd9}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "trowd",
            "\\",
            "tabsnoovrlp",
            "\\",
            "tdfrmtxtLeft180",
            "\\",
            "tdfrmtxtRight180",
            "\\",
            "tphmrg",
            "\\",
            "tposx720",
            "\\",
            "tpvmrg",
            "\\",
            "tposy360",
            "\\",
            "clFitText",
            "\\",
            "cellx1800 Floating",
            "\\",
            "cell",
            "\\",
            "row}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "ftnrestart",
            "\\",
            "ftnrstpg",
            "\\",
            "ftnrstcont",
            "\\",
            "aftnrestart",
            "\\",
            "aftnrstpg",
            "\\",
            "aftnrstcont Body",
            "\\",
            "chftn{",
            "\\",
            "footnote ",
            "\\",
            "chftn Note",
            "\\",
            "par}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "trowd",
            "\\",
            "trpaddfl3",
            "\\",
            "trpaddl240",
            "\\",
            "trspdl120",
            "\\",
            "trspdfl3",
            "\\",
            "clpadfl3",
            "\\",
            "clpadl180",
            "\\",
            "clspdl60",
            "\\",
            "clspdfl3",
            "\\",
            "cellx1800 Unit",
            "\\",
            "cell",
            "\\",
            "row}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "sectd",
            "\\",
            "linex0 Visible distance metadata",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "sectd",
            "\\",
            "pgnx720",
            "\\",
            "pgny720",
            "\\",
            "sectlinegrid360",
            "\\",
            "sectdefaultcl",
            "\\",
            "sectexpand720",
            "\\",
            "sectspecifycl",
            "\\",
            "sectspecifyl",
            "\\",
            "sectunlocked{",
            "\\",
            "header Page ",
            "\\",
            "chpgn",
            "\\",
            "par}Visible section grid",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "themelang1033",
            "\\",
            "dghspace180",
            "\\",
            "dgvspace180",
            "\\",
            "viewbksp1",
            "\\",
            "viewnobound1",
            "\\",
            "formdisp",
            "\\",
            "jexpand",
            "\\",
            "jcompress",
            "\\",
            "asianbrkrule",
            "\\",
            "nogrowautofit",
            "\\",
            "lytexcttp",
            "\\",
            "noextrasprl",
            "\\",
            "htmautsp Visible compatibility",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "stylesheet{",
            "\\",
            "s1 Heading;}}{",
            "\\",
            "s1 Visible heading",
            "\\",
            "par}{",
            "\\",
            "pard {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst STYLEREF Heading}}",
            "\\",
            "par}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "fonttbl{",
            "\\",
            "f0 Arial;}{",
            "\\",
            "f14 Wingdings;}}Before ({",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst SYMBOL 74 \\\\f \"Wingdings\" \\\\s 12}{",
            "\\",
            "fldrslt",
            "\\",
            "f14",
            "\\",
            "fs24}}) After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst ADDIN \"Hidden addin\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst PRIVATE \"414243\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst RD \"C:\\\\secret\\\\source.rtf\"}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst NEXTIF \"City\" = \"Paris\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst MERGEREC}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst MERGESEQ}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst ADDRESSBLOCK \\\\f \"<<_COMPANY_>>\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst GREETINGLINE \\\\f \"<<_LAST0_>>\"}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst ASK Client \"Hidden prompt\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst FILLIN \"Secret prompt\"}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst FILENAME \\\\p}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst USERNAME}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "bkmkstart NoteRef}",
            "\\",
            "chftn{",
            "\\",
            "bkmkend NoteRef}{",
            "\\",
            "footnote Footnote}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst NOTEREF NoteRef}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "version12}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst REVNUM}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "userprops{",
            "\\",
            "propname Client}{",
            "\\",
            "staticval Contoso}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst DOCPROPERTY Client}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "docvar {Client}{Contoso}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst DOCVARIABLE Client}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst SET Client \"Contoso\"}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst REF Client}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "title Safe title}{",
            "\\",
            "author Alice}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst TITLE}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst AUTHOR}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "title Safe title}{",
            "\\",
            "author Alice}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst INFO Title}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst INFO Author}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "creatim",
            "\\",
            "yr2024",
            "\\",
            "mo7",
            "\\",
            "dy5}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst CREATEDATE \\\\@ \"yyyy-MM-dd\"}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst ADVANCE \\\\r 240}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst DATE \\\\@ \"yyyy-MM-dd\"}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst TIME \\\\@ \"HH:mm\"}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "info{",
            "\\",
            "edmins42}}{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst EDITTIME}}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "fonttbl{",
            "\\",
            "f0 Arial;}}Hello}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "fonttbl{",
            "\\",
            "f0 Arial;}{",
            "\\",
            "f1 Wingdings;}}",
            "\\",
            "loch",
            "\\",
            "af1 ",
            "\\",
            "afs72 ",
            "\\",
            "'a3 ",
            "\\",
            "'fe {",
            "\\",
            "object",
            "\\",
            "objdata 414243}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "accdot Dot ",
            "\\",
            "acccomma Comma ",
            "\\",
            "accnone Plain{",
            "\\",
            "object",
            "\\",
            "objdata 414243}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "colortbl;",
            "\\",
            "red255",
            "\\",
            "green0",
            "\\",
            "blue0;}",
            "\\",
            "loch",
            "\\",
            "ab",
            "\\",
            "ai",
            "\\",
            "acf1",
            "\\",
            "aul",
            "\\",
            "aexpnd4",
            "\\",
            "aup6 Associated{",
            "\\",
            "object",
            "\\",
            "objdata 414243}",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "colortbl;",
            "\\",
            "red255",
            "\\",
            "green0",
            "\\",
            "blue0;}Hello}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "stylesheet{",
            "\\",
            "s0 Normal;}}{",
            "\\",
            "latentstyles",
            "\\",
            "lsdstimax376",
            "\\",
            "lsdsemihiddendef1 Hidden{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}Visible",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "trowd",
            "\\",
            "trftsWidth3",
            "\\",
            "trwWidth2880 A",
            "\\",
            "cell B",
            "\\",
            "cell",
            "\\",
            "row}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "object",
            "\\",
            "objocx",
            "\\",
            "objdata 414243}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "object{",
            "\\",
            "objdata 414243}{",
            "\\",
            "result visible fallback}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "object{",
            "\\",
            "objdata 414243}{",
            "\\",
            "result{",
            "\\",
            "pict",
            "\\",
            "jpegblip",
            "\\",
            "picwgoal720",
            "\\",
            "pichgoal720 ffd8ffc00011080001000103011100021100031100ffd9}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "fromhtml1",
            "\\",
            "htmlrtf1",
            "\\",
            "b",
            "\\",
            "htmlrtf0 Visible{",
            "\\",
            "*",
            "\\",
            "htmltag <script>414243</script>}{",
            "\\",
            "htmltag Hidden HTML}{",
            "\\",
            "htmlbase https://example.com/payload} after",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst HYPERLINK \"https://example.com/payload\"}{",
            "\\",
            "fldrslt visible link}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst QUOTE \"mixed Case\" \\\\* Lower \\\\* FirstCap}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst SEQ Figure \\\\r 4 \\\\* ROMAN}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst = 27 \\\\* alphabetic}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst = 1234567 \\\\# \"#,##0\"}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst EQ ",
            "\\",
            "f(1,2)}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst EQ \\\\f(alpha,beta)}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst COMPARE 5 > 3 \\\\* ROMAN}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst COMPARE 1 = 1 HIDDEN-TRAIL}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst TOC \\\\o \"1-3\"}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst BIBLIOGRAPHY}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst AUTOTEXT HiddenBlock}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst BARCODE \"Hidden address\" QR}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst MERGEBARCODE \"Hidden merge value\" QR}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst GOTOBUTTON HiddenBookmark \"Visible jump\"}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst CONTROL Forms.CommandButton.1 \"Hidden caption\"}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst HTMLINPUT \"password\" value=\"secret\"}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst SHAPE \\\\* MERGEFORMAT}{",
            "\\",
            "fldrslt Visible drawing fallback}} {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst SHAPE \\\\* MERGEFORMAT}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst FORMTEXT}{",
            "\\",
            "formfield{",
            "\\",
            "fftype0}{",
            "\\",
            "ffdeftext Safe default}{",
            "\\",
            "ffentrymcr launch.exe}{",
            "\\",
            "datafield 414243}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst FORMCHECKBOX}{",
            "\\",
            "formfield{",
            "\\",
            "fftype1}{",
            "\\",
            "ffres1}{",
            "\\",
            "ffentrymcr launch.exe}{",
            "\\",
            "datafield 414243}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 Before {",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst FORMDROPDOWN}{",
            "\\",
            "formfield{",
            "\\",
            "fftype2}{",
            "\\",
            "*",
            "\\",
            "ffl Safe choice}{",
            "\\",
            "ffentrymcr launch.exe}{",
            "\\",
            "datafield 414243}}} After",
            "\\",
            "par}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1 visible{",
            "\\",
            "annotation hidden {",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "*",
            "\\",
            "unknown{",
            "\\",
            "object",
            "\\",
            "objdata 414243}}}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "shp{",
            "\\",
            "*",
            "\\",
            "shpinst{",
            "\\",
            "sp{",
            "\\",
            "sn pFragments}{",
            "\\",
            "sv calc.exe}}}} visible}",
        ]),
        br#"{\rtf1{\shp{\shpinst\shpleft720\shptop720\shpright2160\shpbottom1440{\sp{\sn shapeType}{\sv 1}}{\sp{\sn pFragments}{\sv calc.exe}}}{\shptxt Box {\field{\*\fldinst HYPERLINK "https://example.com"}{\fldrslt visible}}\par}}}"#.to_vec(),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "background Hidden {",
            "\\",
            "shp{",
            "\\",
            "*",
            "\\",
            "shpinst",
            "\\",
            "shpleft0",
            "\\",
            "shptop0",
            "\\",
            "shpright3000",
            "\\",
            "shpbottom1200{",
            "\\",
            "sp{",
            "\\",
            "sn shapeType}{",
            "\\",
            "sv 1}}{",
            "\\",
            "sp{",
            "\\",
            "sn pFragments}{",
            "\\",
            "sv calc.exe}}}}} visible}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "shp{",
            "\\",
            "*",
            "\\",
            "shpinst",
            "\\",
            "shpleft720",
            "\\",
            "shptop720",
            "\\",
            "shpright2160",
            "\\",
            "shpbottom1440{",
            "\\",
            "sp{",
            "\\",
            "sn shapeType}{",
            "\\",
            "sv 1}}{",
            "\\",
            "sp{",
            "\\",
            "sn pFragments}{",
            "\\",
            "sv calc.exe}}}} visible}",
        ]),
        rtf(&[
            "{",
            "\\",
            "rtf1{",
            "\\",
            "field{",
            "\\",
            "*",
            "\\",
            "fldinst MACROBUTTON launch.exe Click}{",
            "\\",
            "fldrslt Safe caption}}}",
        ]),
        b"{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{".to_vec(),
        rtf(&["{", "\\", "rtf1", "\\", "bin999999999999999999999 abc}"]),
        rtf(&["{", "\\", "rtf1", "\\", "bin-1 abc}"]),
        rtf(&[
            "{",
            "\\",
            "rtf1",
            "\\",
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa text}",
        ]),
    ]
}

fn rtf(parts: &[&str]) -> Vec<u8> {
    let mut output = Vec::new();
    for part in parts {
        output.extend_from_slice(part.as_bytes());
    }
    output
}
